# DeepSeek Harness 桌面快捷方式 - 一键安装脚本（交互式，中文界面）
# 项目: DeepSeek Harness 桌面快捷方式 | 许可证: MIT (见 LICENSE)
# 用法：
#   双击 install.bat（推荐：自动解除下载锁定后调用本脚本）
#   或手动: powershell -ExecutionPolicy Bypass -File install.ps1 [-Path "D:\DeepSeek"]
# 带 -Path 时跳过交互，直接安装到指定目录
param(
    [string]$Path = ''
)
$ErrorActionPreference = 'Stop'
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

$root     = $PSScriptRoot
$assetDir = Join-Path $root 'assets'
$icoSrc   = Join-Path $assetDir 'deepseek.ico'

# 弹窗：是/否（60 秒后自动关闭）
function Show-YesNoPopup {
    param([string]$Text, [string]$Title)
    $wsPopup = New-Object -ComObject WScript.Shell
    $r = $wsPopup.Popup($Text, 60, $Title, 4 + 48)
    return ($r -eq 6)
}

# 弹窗：仅提示（30 秒后自动关闭）
function Show-InfoPopup {
    param([string]$Text, [string]$Title)
    $wsPopup = New-Object -ComObject WScript.Shell
    $null = $wsPopup.Popup($Text, 30, $Title, 0 + 48)
}

# ============ 交互模式：检测 Node.js 与选择安装位置 ============
if ($Path -eq '') {
    Write-Host ''
    Write-Host '============================================' -ForegroundColor Cyan
    Write-Host '  DeepSeek Harness 桌面快捷方式 安装器' -ForegroundColor Cyan
    Write-Host '============================================' -ForegroundColor Cyan
    Write-Host ''

    # 1. 检测 Node.js
    if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
        Write-Host '检测到电脑没有安装 Node.js，DeepSeek Harness 需要它才能运行。' -ForegroundColor Red
        if (Show-YesNoPopup -Text ('检测到电脑没有安装 Node.js，DeepSeek Harness 需要它才能运行。' + "`r`n`r`n" + '是否现在打开下载页面？') -Title '缺少 Node.js') {
            Start-Process 'https://nodejs.org'
        }
        Write-Host '请先安装 Node.js，然后重新运行安装器。' -ForegroundColor Yellow
        return
    }
    Write-Host '已检测到 Node.js。' -ForegroundColor Green
    Write-Host ''

    # 2. 选择安装位置
    Write-Host '选择安装位置：'
    Write-Host '  [1] C 盘（默认，推荐）'
    Write-Host '  [2] D 盘'
    Write-Host '  [3] 自定义路径'
    Write-Host ''
    $choice = Read-Host '请输入 1、2 或 3 后回车'
    switch ($choice) {
        '1' {
            $Path = Join-Path $env:LOCALAPPDATA 'DeepSeek'
        }
        '2' {
            if (Test-Path 'D:\') { $Path = 'D:\DeepSeek' }
            else { Write-Host 'D 盘不存在，改用默认位置。' -ForegroundColor Yellow; $Path = Join-Path $env:LOCALAPPDATA 'DeepSeek' }
        }
        '3' {
            Write-Host '注意：路径不要包含中文或空格，例如 D:\DeepSeek'
            $custom = Read-Host '请输入完整路径'
            if ([string]::IsNullOrWhiteSpace($custom)) {
                $Path = Join-Path $env:LOCALAPPDATA 'DeepSeek'
            } elseif ($custom -match '[\u4e00-\u9fff]') {
                Write-Host '路径包含中文，可能导致无法运行，安装已取消。' -ForegroundColor Red
                Show-InfoPopup -Text '路径包含中文，可能导致无法运行，安装已取消。请重新运行并输入纯英文路径（例如 D:\DeepSeek）。' -Title '路径无效'
                return
            } elseif ($custom -match ' ') {
                Write-Host '路径包含空格，可能引起异常。' -ForegroundColor Yellow
                if (Show-YesNoPopup -Text '路径包含空格，可能引起异常。仍要使用该路径吗？' -Title '路径含空格') {
                    $Path = $custom
                } else {
                    Write-Host '已取消。'
                    return
                }
            } else {
                $Path = $custom
            }
        }
        default {
            Write-Host '输入无效，使用默认 C 盘位置。'
            $Path = Join-Path $env:LOCALAPPDATA 'DeepSeek'
        }
    }
    Write-Host ''
    Write-Host ('安装到：' + $Path)
    Write-Host ''
}

# ============ 执行安装 ============

# 1. 确保图标存在（缺失时自动从官方 SVG 渲染）
if (-not (Test-Path -LiteralPath $icoSrc)) {
    & (Join-Path $root 'render-logo.ps1')
}

# 2. 解析安装目录（规范化为绝对路径）
$iconDir = [System.IO.Path]::GetFullPath($Path.TrimEnd('\'))
if ($iconDir -match '[\u4e00-\u9fff]') {
    throw "安装路径包含中文，可能导致脚本无法运行。请改用纯英文路径（例如 D:\DeepSeek）。当前路径: $iconDir"
}
New-Item -ItemType Directory -Force -Path $iconDir | Out-Null
$icoDst = Join-Path $iconDir 'deepseek-rounded.ico'
Copy-Item -LiteralPath $icoSrc -Destination $icoDst -Force
# 清理旧图标文件：Windows 图标缓存按路径记忆，换新文件名以强制刷新
Remove-Item -LiteralPath (Join-Path $iconDir 'deepseek.ico') -Force -ErrorAction SilentlyContinue
$launcherSrc = Join-Path $root 'start-harness.ps1'
$launcherDst = Join-Path $iconDir 'start-harness.ps1'
if (Test-Path -LiteralPath $launcherSrc) {
    Copy-Item -LiteralPath $launcherSrc -Destination $launcherDst -Force
} else {
    throw "缺少启动器脚本: $launcherSrc"
}
$dispatcherSrc = Join-Path $root 'dispatcher.ps1'
$dispatcherDst = Join-Path $iconDir 'dispatcher.ps1'
if (Test-Path -LiteralPath $dispatcherSrc) {
    Copy-Item -LiteralPath $dispatcherSrc -Destination $dispatcherDst -Force
} else {
    throw "缺少调度器脚本: $dispatcherSrc"
}
# 无窗口入口 dispatcher.vbs 按实际安装路径生成（UTF-16 保存，兼容任意英文路径）
$vbsDst = Join-Path $iconDir 'dispatcher.vbs'
$vbsContent = @"
' DeepSeek Harness launcher entry (windowless). Generated by installer.
Option Explicit
Dim sh, psDir
Set sh = CreateObject("WScript.Shell")
psDir = "$iconDir"
sh.Run "powershell.exe -NoLogo -ExecutionPolicy Bypass -File """ & psDir & "\dispatcher.ps1""", 0, False
"@
[System.IO.File]::WriteAllText($vbsDst, $vbsContent, [System.Text.Encoding]::Unicode)

# 3. 创建桌面快捷方式：经 wscript.exe 启动 VBS 入口（wscript 是无窗口程序，
#    双击时桌面上绝不出现任何窗口）
$desktop = [Environment]::GetFolderPath('Desktop')
$lnkPath = Join-Path $desktop 'DeepSeek Harness.lnk'
$ws = New-Object -ComObject WScript.Shell
$sc = $ws.CreateShortcut($lnkPath)
$sc.TargetPath = Join-Path $env:SystemRoot 'System32\wscript.exe'
$sc.Arguments  = ('"' + $vbsDst + '"')
$sc.WorkingDirectory = $iconDir
$sc.WindowStyle = 1                     # wscript 无窗口，此值无关紧要
$sc.IconLocation = "$icoDst,0"
$sc.Description  = 'DeepSeek Harness - 智能启动：已在运行时不弹窗口，直接唤起浏览器'
$sc.Save()

# 4. 刷新 Windows 图标缓存，让圆角图标立即生效
Add-Type -TypeDefinition @"
using System;
using System.Runtime.InteropServices;
public static class IconRefresh {
    [DllImport("shell32.dll")] public static extern void SHChangeNotify(int wEventId, int uFlags, IntPtr dwItem1, IntPtr dwItem2);
}
"@
[IconRefresh]::SHChangeNotify(0x8000000, 0, [IntPtr]::Zero, [IntPtr]::Zero)   # SHCNE_ASSOCCHANGED
try { & "$env:SystemRoot\System32\ie4uinit.exe" -show | Out-Null } catch {}
Write-Host '图标缓存已刷新。'

Write-Host ''
Write-Host '完成！桌面上已生成 "DeepSeek Harness" 快捷方式：' -ForegroundColor Green
Write-Host ('  ' + $lnkPath)
Write-Host '双击：没在运行 -> 弹出终端并启动；已在运行 -> 只唤起浏览器，不弹任何窗口。'
Write-Host '如果桌面图标仍未变成圆角，右键桌面 -> 刷新即可。'
